name: Bug 反馈
description: 识别错误、操作异常、连接错误等
labels: ["bug"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      description: |
        请确认自己完成了要求之后再进行勾选
      options:
        - label: 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
          required: true
        - label: 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
          required: true
        - label: 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
          required: true
        - label: 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及
          required: true
  - type: textarea
    id: describe
    attributes:
      label: 问题描述
      description: 描述问题时请尽可能详细
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: >-
        请提供 MNMA 版本
      placeholder: |
        MNMA Version:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志和配置文件
      description: |
        **请在关闭 MNMA 后，按如下方式上传反馈文件：**
          1. 运行 MNMA 根目录下的 `反馈打包小工具.exe`
          2. 将打包好的 反馈日志.zip 上传至此处

        如果你在使用 MacBook，请在群内寻求帮助
        **请直接将完整的文件拖拽进来，而非自己裁切或复制的片段；若文件体积过大可压缩后再上传**
      placeholder: |
        请确认上传文件前已关闭 MNMA
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: 配置信息
      description: |
        请说明操作系统及版本、模拟器品牌、模拟器分辨率、DPI、帧率（模拟器设置界面可查看）；
        若您并非使用 MuMu 12 模拟器，请尝试使用，其他模拟器的问题不会修复。
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 截图或录屏
      description: |
        如果能复现问题，请尽可能上传视频
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 还有别的吗？
      description: |
        任何能让我们对你所遇到的问题有更多了解的东西
    validations:
      required: false
